Feat/architecture found rate
jucasero/mobile-ramen-test-jucasero pull request #11
Opened 2022-12-26 22:30 UTC by kareenmartinez

2022-12-27 14:00 UTC, bryan-arriaza-g requested changes

2022-12-27 14:00 UTC, bryan-arriaza-g commented on src/constants/index.js
> +export const routes = {
Este archivo creo que no aplica, contiene rutas de recepción de mercadería
las rutas se manejan a través de `src/routes/index.ts` en este caso creo que deberíamos renombrar este archivo `index.ts` a `src/routes/found-rate.ts`, para identificar que archivos/rutas son de found-rate o las rutas a que modulo pertenecen en archivos separados

2022-12-28 13:41 UTC, bryan-arriaza-g approved these changes

2022-12-28 13:44 UTC, jucasero approved these changes

2022-12-28 13:49 UTC, merged