feat(component): integrated product rack question component
jucasero/mobile-ramen-test-jucasero pull request #17
Opened 2023-01-04 22:30 UTC by kareenmartinez

2023-01-05 13:08 UTC, jucasero commented on src/App.tsx
> -  if (!authenticated) {
se te paso este codigo comentado

2023-01-05 13:27 UTC, bryan-arriaza-g requested changes

2023-01-05 13:27 UTC, bryan-arriaza-g commented on src/components/button/index.tsx
> +    switch (type) {
Sugerencia, podríamos reemplazar el switch por un objeto tipo

```
const styles = () => {
  const btnStyles = {
    primary: 'button--dark',
    secondary: 'button--light',
  };
  return btnStyles[type] || 'button--dark';
};

```

2023-01-05 13:27 UTC, bryan-arriaza-g commented on src/pages/tasks/found-rate/views/productDetail/locales/es.tsx
> +  INFO_TEXT_1: 'Ubicación correcta',
Podríamos reemplazar los textos INFO_TEXT_1, INFO_TEXT_2, INFO_TEXT_3, INFO_TEXT_4 por nombres más descriptivos
ej.
INFO_TEXT_1 => 'CORRECT_LOCATION'

2023-01-06 13:59 UTC, jucasero commented on src/pages/tasks/found-rate/views/productDetail/index.tsx
> +        {true && <ProductInRack />}
esta condicion es innecesaria

2023-01-09 13:49 UTC, bryan-arriaza-g approved these changes

2023-01-10 12:58 UTC, jucasero approved these changes

2023-01-10 12:58 UTC, bryan-arriaza-g approved these changes

2023-01-10 13:06 UTC, merged