Module/communications
jucasero/mobile-ramen-test-jucasero pull request #26
Opened 2023-02-07 18:55 UTC by kareenmartinez

## Tickets
N/A

## Description
En esta PR se encuentra la implementación del nuevo módulo "Comunicaciones" en la aplicación.

## Changelog
- [x] Nuevo botón en la home llamado "Comunicados".
- [x] Listado de categorías, asociadas a los comunicados.
- [x] Listado de comunicados, agrupados por "leídos" y "no leídos".
- [x] Implementación del contexto para manejar la funcionalidad de la lectura de los comunicados. (La integración se realiza en otra PR)

## Screenshots

Categorías
<img width="410" alt="Captura de pantalla 2023-02-07 a la(s) 15 48 03" src="https://user-images.githubusercontent.com/54424256/217337926-37e11346-6d04-4c66-92e0-ec38205426b4.png">

Comunicados
<img width="410" alt="Captura de pantalla 2023-02-07 a la(s) 15 48 12" src="https://user-images.githubusercontent.com/54424256/217337933-b8cd26ca-57c6-4cfd-80e9-6feea74efa7b.png">

2023-02-10 14:14 UTC, jucasero commented on src/clients/FoundRateClient.tsx
> -import { RESTClient } from '@team_eureka/eureka-ionic-core';
Se me hace raro que saliste de main, pero aparecen cambios como si hubieras eliminado cosas de la rama module/foundrate

2023-02-10 14:14 UTC, jucasero commented on src/pages/news/views/news/index.tsx
> +                <span className='communication-text-unread'>
Aqui lo mismo que te comente en la parte de arriba con respecto a el etiquetado html, aparte el texto no deberia estar directo, sino venir de los locales.

2023-02-14 19:18 UTC, bryan-arriaza-g requested changes

2023-02-14 19:18 UTC, bryan-arriaza-g commented on src/pages/news/views/news/locales/br.tsx
> +  COMMUNICATIONS_READ: '',
Agregar los textos correspondientes, esto debido a que si en algún momento se requiere probar la internacionalización los labels se mostrarían como campos en blanco pudiendo dar la impresión que se trata de un issue

2023-02-14 19:18 UTC, bryan-arriaza-g commented on src/pages/news/views/news/locales/en.tsx
> +  COMMUNICATIONS_READ: '',
Lo mismo acá para los textos i18n, agregar los textos correspondientes, esto debido a que si en algún momento se requiere probar la internacionalización los labels se mostrarían como campos en blanco pudiendo dar la impresión que se trata de un issue

2023-02-14 19:18 UTC, bryan-arriaza-g commented on src/pages/root-home/components/news-content/index.tsx
> +  '1': categoryImage,
Se podría hacer refactor de esta función para unificar la lógica de:
https://github.com/jucasero/mobile-ramen-test-jucasero/blob/0051ec8d9a23c5f6b9fc90574184866a15d71fe1/src/pages/news/components/CommunicationCard/index.tsx#L10

De esta forma centralizar el cambio y poder exponer tanto el color:
![image](https://user-images.githubusercontent.com/62806969/218834790-ff25e49f-1ebf-428b-b229-3653034a3427.png)
así como la imagen, en un mismo objeto centralizado,

tipo: 

```
const categoryData = {
  '1': {
    color: '#DA995D',
    icon: categoryImage
  }
}
```
y lo mismo para los siguientes campos
esto podría incluirse en algún **commons** dentro del módulo news

2023-02-17 10:40 UTC, closed without merging