Feat/eslint prettier config found rate
jucasero/mobile-ramen-test-jucasero pull request #9
Opened 2022-12-22 15:12 UTC by jucasero

## Tickets
- [GCX-45: Configuracion de eslint y prettier en el proyecto de arcus](https://cencosud.atlassian.net/browse/GCX-45)

## Description
Pueden mirar solo los archivos de configuracion de eslint y prettier, las otras modificaciones son las que se hicieron automagicamente 🪄. Aparte tambien elimino de git las carpetas android, ios y build 

## Changelog
- [x] chore(build): delete ios, android and build folders
- [x] [chore(.gitignore): remove ios, android and build folders from git](https://github.com/jucasero/mobile-ramen-test-jucasero/commit/23341a91acfa0428cdde607a4b1f2bbf18b25bd3)
- [x] [build(ionicons): add ionicons package](https://github.com/jucasero/mobile-ramen-test-jucasero/commit/c90002e72f18f27505012f9af69ebb12393661bb)
- [x] [chore(eslint): add eslint and prettier config](https://github.com/jucasero/mobile-ramen-test-jucasero/commit/4faa00fec73f6f6d944f0a21dc9c670eadc1e946)
- [x] [style(src): apply linter rules](https://github.com/jucasero/mobile-ramen-test-jucasero/commit/829d6a548879e04f7aef0979f0c0117157eeefb5)

## Screenshots

N/A

2022-12-22 16:29 UTC, kareenmartinez submitted a review, later dismissed

2022-12-22 18:15 UTC, bryan-arriaza-g requested changes
Lo veo bien, más que las mismas observaciones hechas en el PR:
https://github.com/jucasero/mobile-ramen-test-jucasero/pull/8#pullrequestreview-1228058712

2022-12-26 17:24 UTC, bryan-arriaza-g approved these changes

2022-12-26 19:40 UTC, kareenmartinez approved these changes

2022-12-26 20:50 UTC, merged